### ISSUE TITLE
Package returned false "Straight"

### ISSUE THREAD

**Issue by itssigron** [thekoushik/holdem-poker#25]
How are these hands considered Straight? 
![image](https://user-images.githubusercontent.com/52041489/203651221-60dcbc3a-95ef-433b-ac7f-bb05bb8f139f.png)
![image](https://user-images.githubusercontent.com/52041489/203651517-4cdd964c-60cd-4a6f-ab5f-cb28787fd175.png)
How did player 2 got a straight if the 7 is in playey 1's hand?
![image](https://user-images.githubusercontent.com/52041489/203651828-f34b2c47-13b5-463f-aa94-988e118b45b6.png)

**Comment by thekoushik** [comment]
Thanks for pointing out, I'll take a look.
